project_id = "umbvknqvqeokwzwaycta"

[functions.extract-vocabulary]
verify_jwt = false

[functions.pronounce-word]
verify_jwt = false

[functions.transcribe-page]
verify_jwt = false

[functions.lookup-word]
verify_jwt = false
